title: "AgriSynthe"
email: contact@nongnghiepsinhthai.vn
description: >-
  AgriSynthe - Thư viện số tự động tổng hợp, chắt lọc và biên soạn
  kiến thức nông nghiệp hữu cơ bền vững từ các tài liệu khoa học, sách kinh điển bởi Trí tuệ Nhân tạo (AI).
baseurl: "/Agri"
url: "https://manhhuynh-designer.github.io"

# Permalinks for blog posts
permalink: /posts/:title/

# Markdown configurations
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lo-double-barrel-retort.html
